name: Deploy Render Docs on Push

on:
  push:
    branches:
      - main
      - master
      - connectX.backend.refactor_the_model.adane

jobs:
  deploy-render-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST "https://api.render.com/deploy/${RENDER_SERVICE_ID}" 
